kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1
    extraPortMapping:
      - containerPort: 31000
        hostPort: 31000
  - role: worker
    image: kindest/node:v1.33.1
  - role: worker
    image: kindest/node:v1.33.1

# Use:
# kind create cluster --config kind-cluster.yaml --name gaurav-demo
